name: example
version: 1.0.0
description: Example for ffmpeg_cli

publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  ffmpeg_cli:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.3
