name: ffmpeg_cli
version: 0.3.0
description: Run FFMPEG CLI commands from Dart.
homepage: https://github.com/Flutter-Bounty-Hunters/ffmpeg_cli

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  collection: ^1.18.0
  json_annotation: ^4.1.0
  logging: ^1.2.0

dev_dependencies:
  test: ^1.0.0
  flutter_lints: ^2.0.3
  build_runner: ^2.0.0
  json_serializable: ^5.0.0
